name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'  
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf libssl-dev pkg-config build-essential libsqlite3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev

      - name: install frontend dependencies
        run: npm install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__
          releaseName: 'Cloudinary Backup v__VERSION__'
          releaseBody: |
            ## 🎉 New Release!
            
            Download the appropriate file for your platform:
            - **macOS (Apple Silicon)**: `.app.tar.gz` file ending with `aarch64-apple-darwin`
            - **macOS (Intel)**: `.app.tar.gz` file ending with `x86_64-apple-darwin`  
            - **Windows**: `.msi` installer file
            - **Linux**: `.deb` or `.AppImage` file
            
            ## What's New
            See commit history for detailed changes.
            
            ## Installation
            - **macOS**: Extract the `.tar.gz` and drag the app to Applications
            - **Windows**: Run the `.msi` installer
            - **Linux**: Install the `.deb` package or run the `.AppImage`
          releaseDraft: false
          prerelease: false